random_state: 42
split:
  test_size: 0.2
model:
  type: LogisticRegression
  max_iter: 800
  C: 1.0
  class_weight: null
features:
  numeric: ["tenure", "MonthlyCharges", "TotalCharges"]
  categorical: ["Contract", "InternetService", "PaymentMethod", SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "PaperlessBilling"]
label: "Churn"
