name: Deploy MLflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Validate required secrets
      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "ERROR: EC2_HOST is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "ERROR: EC2_SSH_KEY is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "ERROR: DB_PASSWORD is not set"
            exit 1
          fi
          if [ -z "${{ secrets.RDS_ENDPOINT }}" ]; then
            echo "ERROR: RDS_ENDPOINT is not set"
            exit 1
          fi
          if [ -z "${{ secrets.S3_BUCKET }}" ]; then
            echo "ERROR: S3_BUCKET is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
            echo "ERROR: AWS_ACCESS_KEY_ID is not set"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
            echo "ERROR: AWS_SECRET_ACCESS_KEY is not set"
            exit 1
          fi

      # 3️⃣ Build Docker image
      - name: Build MLflow Docker image
        run: docker build -t mlflow-server .

      # 4️⃣ Save Docker image as tar in repo root
      - name: Save Docker image as tar
        run: |
          docker save mlflow-server -o ./mlflow-server.tar
          ls -l ./mlflow-server.tar

      # 5️⃣ Fix tar permissions
      - name: Fix tar file permissions
        run: chmod 644 ./mlflow-server.tar

      # 6️⃣ Copy Docker image to EC2
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./mlflow-server.tar"  # relative path ensures file exists
          target: "~/"

      # 7️⃣ Run MLflow container on EC2
      - name: Run MLflow container on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            sudo docker load -i mlflow-server.tar
            sudo docker stop mlflow || true
            sudo docker rm mlflow || true
            echo "Launching MLflow with backend=$BACKEND_STORE_URI and artifact root=$ARTIFACT_ROOT"
            sudo docker run -d -p 5000:5000 \
              --name mlflow \
              -e BACKEND_STORE_URI=postgresql://mlflow_user:${{ secrets.DB_PASSWORD }}@${{ secrets.RDS_ENDPOINT }}:5432/mlflowdb \
              -e ARTIFACT_ROOT=${{ secrets.S3_BUCKET }} \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              mlflow-server \
              mlflow server \
                --backend-store-uri $BACKEND_STORE_URI \
                --default-artifact-root //${{ secrets.S3_BUCKET }}/mlflow-artifacts \
                --host 0.0.0.0 --port 5000
